//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pedamorf.Service.Client {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConversionOptions", Namespace="http://schemas.datacontract.org/2004/07/Pedamorf.Library")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pedamorf.Service.Client.ImageConversionOptions))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pedamorf.Service.Client.HtmlConversionOptions))]
    public partial class ConversionOptions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pedamorf.Service.Client.PageOrientation OrientationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SilentFailOnUnsupportedTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeoutInSecondsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UsePlaceholderPageOnUnsupportedTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pedamorf.Service.Client.PageOrientation Orientation {
            get {
                return this.OrientationField;
            }
            set {
                if ((this.OrientationField.Equals(value) != true)) {
                    this.OrientationField = value;
                    this.RaisePropertyChanged("Orientation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SilentFailOnUnsupportedType {
            get {
                return this.SilentFailOnUnsupportedTypeField;
            }
            set {
                if ((this.SilentFailOnUnsupportedTypeField.Equals(value) != true)) {
                    this.SilentFailOnUnsupportedTypeField = value;
                    this.RaisePropertyChanged("SilentFailOnUnsupportedType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeoutInSeconds {
            get {
                return this.TimeoutInSecondsField;
            }
            set {
                if ((this.TimeoutInSecondsField.Equals(value) != true)) {
                    this.TimeoutInSecondsField = value;
                    this.RaisePropertyChanged("TimeoutInSeconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UsePlaceholderPageOnUnsupportedType {
            get {
                return this.UsePlaceholderPageOnUnsupportedTypeField;
            }
            set {
                if ((this.UsePlaceholderPageOnUnsupportedTypeField.Equals(value) != true)) {
                    this.UsePlaceholderPageOnUnsupportedTypeField = value;
                    this.RaisePropertyChanged("UsePlaceholderPageOnUnsupportedType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageConversionOptions", Namespace="http://schemas.datacontract.org/2004/07/Pedamorf.Library")]
    [System.SerializableAttribute()]
    public partial class ImageConversionOptions : Pedamorf.Service.Client.ConversionOptions {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ImageHeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ImageWidthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ImageHeight {
            get {
                return this.ImageHeightField;
            }
            set {
                if ((this.ImageHeightField.Equals(value) != true)) {
                    this.ImageHeightField = value;
                    this.RaisePropertyChanged("ImageHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ImageWidth {
            get {
                return this.ImageWidthField;
            }
            set {
                if ((this.ImageWidthField.Equals(value) != true)) {
                    this.ImageWidthField = value;
                    this.RaisePropertyChanged("ImageWidth");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HtmlConversionOptions", Namespace="http://schemas.datacontract.org/2004/07/Pedamorf.Library")]
    [System.SerializableAttribute()]
    public partial class HtmlConversionOptions : Pedamorf.Service.Client.ConversionOptions {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HTTPAuthenticationPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HTTPAuthenticationUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrintMediaTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserStyleSheetUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HTTPAuthenticationPassword {
            get {
                return this.HTTPAuthenticationPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.HTTPAuthenticationPasswordField, value) != true)) {
                    this.HTTPAuthenticationPasswordField = value;
                    this.RaisePropertyChanged("HTTPAuthenticationPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HTTPAuthenticationUsername {
            get {
                return this.HTTPAuthenticationUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.HTTPAuthenticationUsernameField, value) != true)) {
                    this.HTTPAuthenticationUsernameField = value;
                    this.RaisePropertyChanged("HTTPAuthenticationUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PrintMediaType {
            get {
                return this.PrintMediaTypeField;
            }
            set {
                if ((this.PrintMediaTypeField.Equals(value) != true)) {
                    this.PrintMediaTypeField = value;
                    this.RaisePropertyChanged("PrintMediaType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserStyleSheetUrl {
            get {
                return this.UserStyleSheetUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UserStyleSheetUrlField, value) != true)) {
                    this.UserStyleSheetUrlField = value;
                    this.RaisePropertyChanged("UserStyleSheetUrl");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageOrientation", Namespace="http://schemas.datacontract.org/2004/07/Pedamorf.Library")]
    public enum PageOrientation : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Landscape = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Portrait = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedamorfResponse", Namespace="http://schemas.datacontract.org/2004/07/Pedamorf.Service")]
    [System.SerializableAttribute()]
    public partial class PedamorfResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pedamorf.Service.Client.ErrorCodeEnum ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ResultPdfField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pedamorf.Service.Client.ErrorCodeEnum ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ResultPdf {
            get {
                return this.ResultPdfField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultPdfField, value) != true)) {
                    this.ResultPdfField = value;
                    this.RaisePropertyChanged("ResultPdf");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorCodeEnum", Namespace="http://schemas.datacontract.org/2004/07/Pedamorf.Service")]
    public enum ErrorCodeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ENGINE_ERROR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COULD_NOT_FETCH_URL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNSUPPORTED_SOURCE = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNSPECIFIED_ERROR = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TIMEOUT = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTHER = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.Client.IPedamorfService")]
    public interface IPedamorfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedamorfService/ConvertUrl", ReplyAction="http://tempuri.org/IPedamorfService/ConvertUrlResponse")]
        Pedamorf.Service.Client.PedamorfResponse ConvertUrl(string url, Pedamorf.Service.Client.HtmlConversionOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedamorfService/ConvertUrls", ReplyAction="http://tempuri.org/IPedamorfService/ConvertUrlsResponse")]
        Pedamorf.Service.Client.PedamorfResponse ConvertUrls(System.Collections.Generic.List<string> urls, Pedamorf.Service.Client.HtmlConversionOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedamorfService/ConvertText", ReplyAction="http://tempuri.org/IPedamorfService/ConvertTextResponse")]
        Pedamorf.Service.Client.PedamorfResponse ConvertText(string text, Pedamorf.Service.Client.ConversionOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedamorfService/ConvertFile", ReplyAction="http://tempuri.org/IPedamorfService/ConvertFileResponse")]
        Pedamorf.Service.Client.PedamorfResponse ConvertFile(byte[] file, string fileName, Pedamorf.Service.Client.ConversionOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedamorfService/ConvertFiles", ReplyAction="http://tempuri.org/IPedamorfService/ConvertFilesResponse")]
        Pedamorf.Service.Client.PedamorfResponse ConvertFiles(System.Collections.Generic.Dictionary<string, byte[]> files, Pedamorf.Service.Client.ConversionOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedamorfService/ConvertImage", ReplyAction="http://tempuri.org/IPedamorfService/ConvertImageResponse")]
        Pedamorf.Service.Client.PedamorfResponse ConvertImage(byte[] image, string fileName, Pedamorf.Service.Client.ImageConversionOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedamorfService/ConvertImages", ReplyAction="http://tempuri.org/IPedamorfService/ConvertImagesResponse")]
        Pedamorf.Service.Client.PedamorfResponse ConvertImages(System.Collections.Generic.Dictionary<string, byte[]> images, Pedamorf.Service.Client.ImageConversionOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedamorfService/ConvertHtml", ReplyAction="http://tempuri.org/IPedamorfService/ConvertHtmlResponse")]
        Pedamorf.Service.Client.PedamorfResponse ConvertHtml(string html, Pedamorf.Service.Client.HtmlConversionOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedamorfService/ConvertHtmlList", ReplyAction="http://tempuri.org/IPedamorfService/ConvertHtmlListResponse")]
        Pedamorf.Service.Client.PedamorfResponse ConvertHtmlList(System.Collections.Generic.List<string> html, Pedamorf.Service.Client.HtmlConversionOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedamorfService/CombinePdfs", ReplyAction="http://tempuri.org/IPedamorfService/CombinePdfsResponse")]
        Pedamorf.Service.Client.PedamorfResponse CombinePdfs(System.Collections.Generic.List<byte[]> sourcePdfs, Pedamorf.Service.Client.ConversionOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedamorfService/ConvertZipFile", ReplyAction="http://tempuri.org/IPedamorfService/ConvertZipFileResponse")]
        Pedamorf.Service.Client.PedamorfResponse ConvertZipFile(byte[] zipFile, Pedamorf.Service.Client.ConversionOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedamorfService/IsFileTypeSupported", ReplyAction="http://tempuri.org/IPedamorfService/IsFileTypeSupportedResponse")]
        bool IsFileTypeSupported(string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedamorfServiceChannel : Pedamorf.Service.Client.IPedamorfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedamorfServiceClient : System.ServiceModel.ClientBase<Pedamorf.Service.Client.IPedamorfService>, Pedamorf.Service.Client.IPedamorfService {
        
        public PedamorfServiceClient() {
        }
        
        public PedamorfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedamorfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedamorfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedamorfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pedamorf.Service.Client.PedamorfResponse ConvertUrl(string url, Pedamorf.Service.Client.HtmlConversionOptions options) {
            return base.Channel.ConvertUrl(url, options);
        }
        
        public Pedamorf.Service.Client.PedamorfResponse ConvertUrls(System.Collections.Generic.List<string> urls, Pedamorf.Service.Client.HtmlConversionOptions options) {
            return base.Channel.ConvertUrls(urls, options);
        }
        
        public Pedamorf.Service.Client.PedamorfResponse ConvertText(string text, Pedamorf.Service.Client.ConversionOptions options) {
            return base.Channel.ConvertText(text, options);
        }
        
        public Pedamorf.Service.Client.PedamorfResponse ConvertFile(byte[] file, string fileName, Pedamorf.Service.Client.ConversionOptions options) {
            return base.Channel.ConvertFile(file, fileName, options);
        }
        
        public Pedamorf.Service.Client.PedamorfResponse ConvertFiles(System.Collections.Generic.Dictionary<string, byte[]> files, Pedamorf.Service.Client.ConversionOptions options) {
            return base.Channel.ConvertFiles(files, options);
        }
        
        public Pedamorf.Service.Client.PedamorfResponse ConvertImage(byte[] image, string fileName, Pedamorf.Service.Client.ImageConversionOptions options) {
            return base.Channel.ConvertImage(image, fileName, options);
        }
        
        public Pedamorf.Service.Client.PedamorfResponse ConvertImages(System.Collections.Generic.Dictionary<string, byte[]> images, Pedamorf.Service.Client.ImageConversionOptions options) {
            return base.Channel.ConvertImages(images, options);
        }
        
        public Pedamorf.Service.Client.PedamorfResponse ConvertHtml(string html, Pedamorf.Service.Client.HtmlConversionOptions options) {
            return base.Channel.ConvertHtml(html, options);
        }
        
        public Pedamorf.Service.Client.PedamorfResponse ConvertHtmlList(System.Collections.Generic.List<string> html, Pedamorf.Service.Client.HtmlConversionOptions options) {
            return base.Channel.ConvertHtmlList(html, options);
        }
        
        public Pedamorf.Service.Client.PedamorfResponse CombinePdfs(System.Collections.Generic.List<byte[]> sourcePdfs, Pedamorf.Service.Client.ConversionOptions options) {
            return base.Channel.CombinePdfs(sourcePdfs, options);
        }
        
        public Pedamorf.Service.Client.PedamorfResponse ConvertZipFile(byte[] zipFile, Pedamorf.Service.Client.ConversionOptions options) {
            return base.Channel.ConvertZipFile(zipFile, options);
        }
        
        public bool IsFileTypeSupported(string fileName) {
            return base.Channel.IsFileTypeSupported(fileName);
        }
    }
}
